---
title: "Some interesting plots about NY NOAA dataset"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

The data of these plots are from NY_NOAA

```{r}
data("ny_noaa")

set.seed(1)

ny_noaa = 
  ny_noaa %>% 
  drop_na(prcp, snow, tmin, tmax, snwd) %>% 
  mutate(
    tmin = as.numeric(tmin),
    tmax = as.numeric(tmax)
  ) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  filter(id %in% c("USW00094728", "USW00094794","USW00094789")) %>% 
  mutate(
    name = recode(id, "USW00094728" = "CentralPark_NY",
                      "USW00094794" = "UTICA_ONEIDA_CO_AP_NY",
                      "USW00094789" = "JFK_Intl_AP_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10
  ) %>% 
  select(-id) %>% 
  sample_n(5000)
```


Column {data-width=600}
-----------------------------------------------------------------------

### Scatter plot of tmax and tmin

```{r}
ny_noaa %>% 
  plot_ly(x = ~tmax, y = ~tmin, type = "scatter", mode = "markers", 
          color = ~name, alpha = 0.5)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Bar chart of total snow for each in each site

```{r}
ny_noaa %>% 
  group_by(year, name) %>% 
  mutate(total_snow = sum(snow)) %>% 
  plot_ly(x = ~year, y = ~total_snow, type = "bar", color = ~name)
```

### Box plot of precipitation for each year in central part

```{r}
ny_noaa %>% 
  filter(name == "CentralPark_NY", prcp != 0) %>% 
  mutate(year = fct_reorder(year, prcp)) %>% 
  plot_ly(x = ~year , y = ~prcp, type = "box")
```

